export const PRODUCT_NAME = 'SkillPilot-AI'
export const TAGLINE = 'Reasoning Agents for Enterprise Certification'
export const PITCH_TAGLINE = 'Your skills pilot — grounded, validated, approved.'
export const HERO_LINE = 'From "I want to get certified" to exam-ready.'
export const LEAGUE = 'Microsoft Agents League · Battle #2: Reasoning Agents'
