export const PRODUCT_NAME = 'SkillPilot-AI'
export const TAGLINE = 'Reasoning Agents for Enterprise Certification'
export const TAGLINE_SHORT = 'Reasoning Agents'
export const PITCH_TAGLINE = 'Your skills pilot — grounded, validated, approved.'
export const LEAGUE = 'Microsoft Agents League · Battle #2: Reasoning Agents'
